Lections/Lections/Controllers/LectionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Lections.Models;
using Lections.Services;
using Microsoft.AspNetCore.Mvc;

namespace Lections.Controllers
{
    public class LectionsController : Controller
    {
        UserService uS;
        LectionService lS;
        LikeService lkS;

        public LectionsController(DatabaseContext context)
        {
            uS = new UserService(context);
            lS = new LectionService(context);
            lkS = new LikeService(context);
        }

        public IActionResult subjAsc()
        {
            return View("AllLections", lS.getAllLections().OrderBy(n => n.subject));
        }
        public IActionResult subjDsc()
        {
            return View("AllLections", lS.getAllLections().OrderByDescending(n => n.subject));
        }

        public IActionResult nameAsc()
        {
            return View("AllLections", lS.getLectionsByUser(uS.getUserIdByName(User.Identity.Name)).OrderBy(n => n.name));
        }

        public IActionResult nameDsc()
        {
            return View("AllLections", lS.getLectionsByUser(uS.getUserIdByName(User.Identity.Name)).OrderByDescending(n => n.name));
        }

        public IActionResult starsAsc()
        {
            return View("AllLections", lS.getLectionsByUser(uS.getUserIdByName(User.Identity.Name)).OrderBy(n => n.stars));
        }

        public IActionResult starsDsc()
        {
            return View("AllLections", lS.getLectionsByUser(uS.getUserIdByName(User.Identity.Name)).OrderByDescending(n => n.stars));
        }

        public IActionResult cDateAsc()
        {
            return View("AllLections", lS.getLectionsByUser(uS.getUserIdByName(User.Identity.Name)).OrderBy(n => n.dateCreate));
        }

        public IActionResult cDateDsc()
        {
            return View("AllLections", lS.getLectionsByUser(uS.getUserIdByName(User.Identity.Name)).OrderByDescending(n => n.dateCreate));
        }

        public IActionResult uDateAsc()
        {
            return View("AllLections", lS.getLectionsByUser(uS.getUserIdByName(User.Identity.Name)).OrderBy(n => n.dateUpdate));
        }

        public IActionResult uDateDsc()
        {
            return View("AllLections", lS.getLectionsByUser(uS.getUserIdByName(User.Identity.Name)).OrderByDescending(n => n.dateUpdate));
        }

        public IActionResult CreateLection()
        {
            return View();
        }

        public IActionResult ShowText(string name)
        {
            Lection l = lS.getAuthorByLName(name);
            ViewBag.usName = uS.getUserNameById(l.UserId);
            return View("ShowLection", lS.getLectionByName(name));

        }

        public IActionResult UpdateLection([FromForm] Lection l)
        {
            Lection lection = lS.getLectionByName(l.name);

            lection.smallDescription = l.smallDescription;
            lection.text = l.text;
            lection.dateUpdate = DateTime.Now;
            lS.updateUserLection(lection);
            lS.Save();
            return View("AllLections", lS.getAllLections());
        }

        public IActionResult AllLections()
        {
            return View(lS.getLectionsByUser(uS.getUserIdByName(User.Identity.Name)));
        }

        public IActionResult LectionEdit(string name)
        {
            return View("EditLection", lS.getLectionByName(name));
        }

        [HttpGet]
        public IActionResult getStars(string star, string name)
        {
            Lection l = lS.getAuthorByLName(name);
            if (!lkS.checkExistLike (uS.getUserbyName(User.Identity.Name).Id, lS.getLectionByName(name).Id))
            {
                Likes like = new Likes();
                like.userStar = Convert.ToInt32(star);
                like.LectionId = lS.getLectionByName(name).Id;
                like.UserId = uS.getUserbyName(User.Identity.Name).Id;
                lkS.addLike(like);
                lkS.Save();
                lS.likeLection(lS.getLectionByName(name).Id, lkS.getNowRating(lS.getLectionByName(name).Id));
                lS.Save();
              
                User user = uS.getUserById(l.UserId);
                user.ammountStars++;
                uS.plusStar(user);
                uS.Save();
               
            }
            else
            {
               Likes like = lkS.getLikeById(uS.getUserbyName(User.Identity.Name).Id, lS.getLectionByName(name).Id);
                like.userStar = Convert.ToInt32(star);
                lkS.updateLike(like);
                lkS.Save();
                lS.likeLection(lS.getLectionByName(name).Id, lkS.getNowRating(lS.getLectionByName(name).Id));
                lS.Save();
            }

            ViewBag.usName = uS.getUserNameById(l.UserId);
            return View("ShowLection", lS.getLectionByName(name));
        }


        public IActionResult LectionDelete(string name)
        {
            lS.deleteUserLection(lS.getLectionByName(name));
            User user = uS.getUserbyName(User.Identity.Name);
            lS.Save();
            user.ammountLections--;
            uS.minusLection(user);
            uS.Save();
            return View("AllLections", lS.getAllLections());
        }

        public IActionResult SaveLection([FromForm] Lection lection)
        {            
            if(lS.checkExistLectionName(lection.name))
            {
                lection.UserId = uS.getUserIdByName(User.Identity.Name);
                lection.dateCreate = DateTime.Now;
                lection.dateUpdate = DateTime.Now;
                lS.createUserLection(lection);
                lS.Save();
                User user = uS.getUserbyName(User.Identity.Name);
                user.ammountLections++;
                uS.plusLection(user);
                uS.Save();
                return View("AllLections", lS.getAllLections());
            }
            else
            {
                ViewBag.message = "Lection name exist";
                return View("CreateLection");
            }
            
        }
    }
}

Lections/Lections/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Lections</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">        
            <div class="navbar-collapse collapse">
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Main Page</a>
                @if (User.Identity.IsAuthenticated)
    {
            <a asp-area="" asp-controller="Lections" asp-action="AllLections" class="navbar-brand"> My Lections</a>
            <a asp-area="" asp-controller="Profile" asp-action="checkAdminU" class="navbar-brand"> Manage Users</a>
            <a asp-area="" asp-controller="Profile" asp-action="checkAdminL" class="navbar-brand"> Manage Lections</a>
            <a asp-area="" asp-controller="Lections" asp-action="CreateLection" class="navbar-brand"> Create Lection</a>
            <div class="col-sm-3 col-md-3">
                <form class="navbar-form" navbar-right" role="search">
                    <div class="input-group">
                        <input type="text" class="form-control" placeholder="Search" name="inputSearch">
                        <div class="input-group-btn">
                            <button asp-controller="Home" asp-action="SearchLections" class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
                        </div>
                    </div>
                </form>
            </div>
            <ul class="nav navbar-nav navbar-right">
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"> @User.Identity.Name <span class="caret"></span> </a>
                    <ul class="dropdown-menu" role="menu">
                        <li><a asp-controller="Profile" asp-action="Index">Profile</a></li>
                        <li><a asp-controller="Authorization" asp-action="SignOut">Sign Out</a></li>
                    </ul>
            </ul>
}
else
{
            <a asp-area="" asp-controller="Authorization" asp-action="Login" class="navbar-brand">Sign In</a>
}
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()

        <footer></footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>

    <script>
        $(document).ready(function () {
            $(".dropdown").hover(
                function () {
                    $('.dropdown-menu', this).not('.in .dropdown-menu').stop(true, true).slideDown("400");
                    $(this).toggleClass('open');
                },
                function () {
                    $('.dropdown-menu', this).not('.in .dropdown-menu').stop(true, true).slideUp("400");
                    $(this).toggleClass('open');
                }
            );
        });
    </script>

    @RenderSection("Scripts", required: false)
</body>
</html>